name: lab_3_1_1
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publication

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Updated http package version
  cupertino_icons: ^1.0.6
  get: ^4.6.5  # Add this line for GetX package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# Your flutter settings go here
